// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: heimdallv2/topup/query.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/0xPolygon/heimdall-v2/types"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QuerySequenceParams is the request type for the TopupTxStatus RPC method
type QuerySequenceParams struct {
	TxHash   string `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	LogIndex uint64 `protobuf:"varint,2,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
}

func (m *QuerySequenceParams) Reset()         { *m = QuerySequenceParams{} }
func (m *QuerySequenceParams) String() string { return proto.CompactTextString(m) }
func (*QuerySequenceParams) ProtoMessage()    {}
func (*QuerySequenceParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fb53cd446974424, []int{0}
}
func (m *QuerySequenceParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySequenceParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySequenceParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySequenceParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySequenceParams.Merge(m, src)
}
func (m *QuerySequenceParams) XXX_Size() int {
	return m.Size()
}
func (m *QuerySequenceParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySequenceParams.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySequenceParams proto.InternalMessageInfo

func (m *QuerySequenceParams) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *QuerySequenceParams) GetLogIndex() uint64 {
	if m != nil {
		return m.LogIndex
	}
	return 0
}

// QuerySequenceParamsResponse the is response type for the TopupTxStatus RPC
// method
type QuerySequenceParamsResponse struct {
	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *QuerySequenceParamsResponse) Reset()         { *m = QuerySequenceParamsResponse{} }
func (m *QuerySequenceParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySequenceParamsResponse) ProtoMessage()    {}
func (*QuerySequenceParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fb53cd446974424, []int{1}
}
func (m *QuerySequenceParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySequenceParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySequenceParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySequenceParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySequenceParamsResponse.Merge(m, src)
}
func (m *QuerySequenceParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySequenceParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySequenceParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySequenceParamsResponse proto.InternalMessageInfo

func (m *QuerySequenceParamsResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

// QueryDividendAccountParams is the request type for the
// DividendAccountByAddress RPC method
type QueryDividendAccountParams struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"user_addr"`
}

func (m *QueryDividendAccountParams) Reset()         { *m = QueryDividendAccountParams{} }
func (m *QueryDividendAccountParams) String() string { return proto.CompactTextString(m) }
func (*QueryDividendAccountParams) ProtoMessage()    {}
func (*QueryDividendAccountParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fb53cd446974424, []int{2}
}
func (m *QueryDividendAccountParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDividendAccountParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDividendAccountParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDividendAccountParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDividendAccountParams.Merge(m, src)
}
func (m *QueryDividendAccountParams) XXX_Size() int {
	return m.Size()
}
func (m *QueryDividendAccountParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDividendAccountParams.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDividendAccountParams proto.InternalMessageInfo

func (m *QueryDividendAccountParams) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryDividendAccountParamsResponse the is response type for the
// DividendAccountByAddress RPC method
type QueryDividendAccountParamsResponse struct {
	Height          string                `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	DividendAccount types.DividendAccount `protobuf:"bytes,2,opt,name=dividend_account,json=dividendAccount,proto3" json:"result"`
}

func (m *QueryDividendAccountParamsResponse) Reset()         { *m = QueryDividendAccountParamsResponse{} }
func (m *QueryDividendAccountParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDividendAccountParamsResponse) ProtoMessage()    {}
func (*QueryDividendAccountParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fb53cd446974424, []int{3}
}
func (m *QueryDividendAccountParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDividendAccountParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDividendAccountParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDividendAccountParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDividendAccountParamsResponse.Merge(m, src)
}
func (m *QueryDividendAccountParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDividendAccountParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDividendAccountParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDividendAccountParamsResponse proto.InternalMessageInfo

func (m *QueryDividendAccountParamsResponse) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *QueryDividendAccountParamsResponse) GetDividendAccount() types.DividendAccount {
	if m != nil {
		return m.DividendAccount
	}
	return types.DividendAccount{}
}

// QueryDividendAccountRootParams is the request type for the
// DividendAccountRoot RPC method
type QueryDividendAccountRootParams struct {
}

func (m *QueryDividendAccountRootParams) Reset()         { *m = QueryDividendAccountRootParams{} }
func (m *QueryDividendAccountRootParams) String() string { return proto.CompactTextString(m) }
func (*QueryDividendAccountRootParams) ProtoMessage()    {}
func (*QueryDividendAccountRootParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fb53cd446974424, []int{4}
}
func (m *QueryDividendAccountRootParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDividendAccountRootParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDividendAccountRootParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDividendAccountRootParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDividendAccountRootParams.Merge(m, src)
}
func (m *QueryDividendAccountRootParams) XXX_Size() int {
	return m.Size()
}
func (m *QueryDividendAccountRootParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDividendAccountRootParams.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDividendAccountRootParams proto.InternalMessageInfo

// QueryDividendAccountRootResponse the is response type for the
// DividendAccountRoot RPC method
type QueryDividendAccountRootResponse struct {
	Height          string              `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	AccountRootHash *types.HeimdallHash `protobuf:"bytes,2,opt,name=account_root_hash,json=accountRootHash,proto3" json:"result"`
}

func (m *QueryDividendAccountRootResponse) Reset()         { *m = QueryDividendAccountRootResponse{} }
func (m *QueryDividendAccountRootResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDividendAccountRootResponse) ProtoMessage()    {}
func (*QueryDividendAccountRootResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fb53cd446974424, []int{5}
}
func (m *QueryDividendAccountRootResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDividendAccountRootResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDividendAccountRootResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDividendAccountRootResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDividendAccountRootResponse.Merge(m, src)
}
func (m *QueryDividendAccountRootResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDividendAccountRootResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDividendAccountRootResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDividendAccountRootResponse proto.InternalMessageInfo

func (m *QueryDividendAccountRootResponse) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *QueryDividendAccountRootResponse) GetAccountRootHash() *types.HeimdallHash {
	if m != nil {
		return m.AccountRootHash
	}
	return nil
}

// QueryVerifyAccountProofParams is the request type for the VerifyAccountProof
// RPC method
type QueryVerifyAccountProofParams struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"user_addr"`
	Proof   string `protobuf:"bytes,2,opt,name=proof,proto3" json:"account_proof"`
}

func (m *QueryVerifyAccountProofParams) Reset()         { *m = QueryVerifyAccountProofParams{} }
func (m *QueryVerifyAccountProofParams) String() string { return proto.CompactTextString(m) }
func (*QueryVerifyAccountProofParams) ProtoMessage()    {}
func (*QueryVerifyAccountProofParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fb53cd446974424, []int{6}
}
func (m *QueryVerifyAccountProofParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVerifyAccountProofParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVerifyAccountProofParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVerifyAccountProofParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVerifyAccountProofParams.Merge(m, src)
}
func (m *QueryVerifyAccountProofParams) XXX_Size() int {
	return m.Size()
}
func (m *QueryVerifyAccountProofParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVerifyAccountProofParams.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVerifyAccountProofParams proto.InternalMessageInfo

func (m *QueryVerifyAccountProofParams) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryVerifyAccountProofParams) GetProof() string {
	if m != nil {
		return m.Proof
	}
	return ""
}

// QueryVerifyAccountProofResponse the is response type for the
// VerifyAccountProof RPC method
type QueryVerifyAccountProofResponse struct {
	// TODO HV2: check VerifyAccountProofHandlerFn where result can also be
	// embedded in a map. In case, implement it.
	Height string `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	Result bool   `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *QueryVerifyAccountProofResponse) Reset()         { *m = QueryVerifyAccountProofResponse{} }
func (m *QueryVerifyAccountProofResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVerifyAccountProofResponse) ProtoMessage()    {}
func (*QueryVerifyAccountProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fb53cd446974424, []int{7}
}
func (m *QueryVerifyAccountProofResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVerifyAccountProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVerifyAccountProofResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVerifyAccountProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVerifyAccountProofResponse.Merge(m, src)
}
func (m *QueryVerifyAccountProofResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVerifyAccountProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVerifyAccountProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVerifyAccountProofResponse proto.InternalMessageInfo

func (m *QueryVerifyAccountProofResponse) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *QueryVerifyAccountProofResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// QueryDividendAccountProofParams is the request type for the
// DividendAccountProof RPC method
type QueryDividendAccountProofParams struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"user_addr"`
}

func (m *QueryDividendAccountProofParams) Reset()         { *m = QueryDividendAccountProofParams{} }
func (m *QueryDividendAccountProofParams) String() string { return proto.CompactTextString(m) }
func (*QueryDividendAccountProofParams) ProtoMessage()    {}
func (*QueryDividendAccountProofParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fb53cd446974424, []int{8}
}
func (m *QueryDividendAccountProofParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDividendAccountProofParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDividendAccountProofParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDividendAccountProofParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDividendAccountProofParams.Merge(m, src)
}
func (m *QueryDividendAccountProofParams) XXX_Size() int {
	return m.Size()
}
func (m *QueryDividendAccountProofParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDividendAccountProofParams.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDividendAccountProofParams proto.InternalMessageInfo

func (m *QueryDividendAccountProofParams) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryDividendAccountProofResponse the is response type for the
// DividendAccountProof RPC method
type QueryDividendAccountProofResponse struct {
	Height string                `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	Result *DividendAccountProof `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *QueryDividendAccountProofResponse) Reset()         { *m = QueryDividendAccountProofResponse{} }
func (m *QueryDividendAccountProofResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDividendAccountProofResponse) ProtoMessage()    {}
func (*QueryDividendAccountProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fb53cd446974424, []int{9}
}
func (m *QueryDividendAccountProofResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDividendAccountProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDividendAccountProofResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDividendAccountProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDividendAccountProofResponse.Merge(m, src)
}
func (m *QueryDividendAccountProofResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDividendAccountProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDividendAccountProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDividendAccountProofResponse proto.InternalMessageInfo

func (m *QueryDividendAccountProofResponse) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *QueryDividendAccountProofResponse) GetResult() *DividendAccountProof {
	if m != nil {
		return m.Result
	}
	return nil
}

// DividendAccountProof embeds user and account info for the the
// QueryDividendAccountProofResponse
type DividendAccountProof struct {
	User         string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AccountProof string `protobuf:"bytes,2,opt,name=account_proof,json=accountProof,proto3" json:"account_proof,omitempty"`
	Index        uint64 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *DividendAccountProof) Reset()         { *m = DividendAccountProof{} }
func (m *DividendAccountProof) String() string { return proto.CompactTextString(m) }
func (*DividendAccountProof) ProtoMessage()    {}
func (*DividendAccountProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fb53cd446974424, []int{10}
}
func (m *DividendAccountProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DividendAccountProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DividendAccountProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DividendAccountProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DividendAccountProof.Merge(m, src)
}
func (m *DividendAccountProof) XXX_Size() int {
	return m.Size()
}
func (m *DividendAccountProof) XXX_DiscardUnknown() {
	xxx_messageInfo_DividendAccountProof.DiscardUnknown(m)
}

var xxx_messageInfo_DividendAccountProof proto.InternalMessageInfo

func (m *DividendAccountProof) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *DividendAccountProof) GetAccountProof() string {
	if m != nil {
		return m.AccountProof
	}
	return ""
}

func (m *DividendAccountProof) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*QuerySequenceParams)(nil), "heimdallv2.topup.QuerySequenceParams")
	proto.RegisterType((*QuerySequenceParamsResponse)(nil), "heimdallv2.topup.QuerySequenceParamsResponse")
	proto.RegisterType((*QueryDividendAccountParams)(nil), "heimdallv2.topup.QueryDividendAccountParams")
	proto.RegisterType((*QueryDividendAccountParamsResponse)(nil), "heimdallv2.topup.QueryDividendAccountParamsResponse")
	proto.RegisterType((*QueryDividendAccountRootParams)(nil), "heimdallv2.topup.QueryDividendAccountRootParams")
	proto.RegisterType((*QueryDividendAccountRootResponse)(nil), "heimdallv2.topup.QueryDividendAccountRootResponse")
	proto.RegisterType((*QueryVerifyAccountProofParams)(nil), "heimdallv2.topup.QueryVerifyAccountProofParams")
	proto.RegisterType((*QueryVerifyAccountProofResponse)(nil), "heimdallv2.topup.QueryVerifyAccountProofResponse")
	proto.RegisterType((*QueryDividendAccountProofParams)(nil), "heimdallv2.topup.QueryDividendAccountProofParams")
	proto.RegisterType((*QueryDividendAccountProofResponse)(nil), "heimdallv2.topup.QueryDividendAccountProofResponse")
	proto.RegisterType((*DividendAccountProof)(nil), "heimdallv2.topup.DividendAccountProof")
}

func init() { proto.RegisterFile("heimdallv2/topup/query.proto", fileDescriptor_6fb53cd446974424) }

var fileDescriptor_6fb53cd446974424 = []byte{
	// 848 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x96, 0x4d, 0x6b, 0xdb, 0x48,
	0x18, 0xc7, 0xad, 0x6c, 0xec, 0xc4, 0x93, 0xcd, 0x26, 0x99, 0x84, 0x25, 0x91, 0x13, 0xd9, 0x11,
	0x6c, 0xde, 0x36, 0x96, 0x12, 0x27, 0x2c, 0x2c, 0xec, 0x1e, 0x62, 0xb2, 0x90, 0x3d, 0x35, 0x75,
	0x42, 0xa1, 0x2f, 0x60, 0x14, 0x6b, 0x22, 0x0b, 0x64, 0x8d, 0xa3, 0x17, 0x63, 0x37, 0xf4, 0xd2,
	0x53, 0x7b, 0x28, 0x14, 0x7a, 0x2f, 0xf4, 0xd6, 0x63, 0x0b, 0xa5, 0xa5, 0xdf, 0x20, 0xc7, 0xd0,
	0x5e, 0x7a, 0x32, 0x25, 0x29, 0x14, 0xf2, 0x11, 0x7a, 0x2a, 0x9a, 0x19, 0x59, 0xb6, 0x6c, 0x51,
	0xa5, 0x97, 0x10, 0x3d, 0xf3, 0x9f, 0xe7, 0xf9, 0x3d, 0x2f, 0x7a, 0x64, 0x30, 0x5f, 0x45, 0x7a,
	0x4d, 0x55, 0x0c, 0xa3, 0x51, 0x90, 0x1d, 0x5c, 0x77, 0xeb, 0xf2, 0x89, 0x8b, 0xac, 0x96, 0x54,
	0xb7, 0xb0, 0x83, 0xe1, 0x64, 0x70, 0x2a, 0x91, 0x53, 0x7e, 0xae, 0x82, 0xed, 0x1a, 0xb6, 0xcb,
	0xe4, 0x5c, 0xa6, 0x0f, 0x54, 0xcc, 0x67, 0xe8, 0x13, 0x75, 0x20, 0x37, 0x36, 0xbb, 0x3d, 0xf1,
	0x53, 0x4a, 0x4d, 0x37, 0xb1, 0x4c, 0xfe, 0x32, 0xd3, 0x8c, 0x86, 0x35, 0x4c, 0xfd, 0x78, 0xff,
	0x31, 0xeb, 0xbc, 0x86, 0xb1, 0x66, 0x20, 0x59, 0xa9, 0xeb, 0xb2, 0x62, 0x9a, 0xd8, 0x51, 0x1c,
	0x1d, 0x9b, 0x7e, 0x8c, 0xe5, 0x6e, 0xdc, 0x56, 0x1d, 0xd9, 0xb2, 0xaa, 0x37, 0x74, 0x15, 0x99,
	0x6a, 0x59, 0xa9, 0x54, 0xb0, 0x6b, 0x3a, 0x3e, 0x4c, 0x9f, 0xb0, 0xaa, 0xd8, 0x55, 0x7a, 0x28,
	0xde, 0x06, 0xd3, 0x37, 0x3d, 0xb6, 0x03, 0x74, 0xe2, 0x22, 0xb3, 0x82, 0xf6, 0x15, 0x4b, 0xa9,
	0xd9, 0x50, 0x00, 0x23, 0x4e, 0xb3, 0xec, 0xe9, 0x66, 0xb9, 0x1c, 0xb7, 0x92, 0x2e, 0x26, 0x5f,
	0x7e, 0x7d, 0xb5, 0xc6, 0x95, 0x52, 0x4e, 0x73, 0x4f, 0xb1, 0xab, 0x50, 0x04, 0x69, 0x03, 0x6b,
	0x65, 0xdd, 0x54, 0x51, 0x73, 0x76, 0x28, 0xc7, 0xad, 0x0c, 0xfb, 0x8a, 0x51, 0x03, 0x6b, 0xff,
	0x7b, 0x66, 0xf1, 0x1f, 0x90, 0x19, 0xe0, 0xba, 0x84, 0xec, 0x3a, 0x36, 0x6d, 0x04, 0x17, 0x40,
	0xca, 0x76, 0x14, 0xc7, 0xb5, 0x49, 0x84, 0xd1, 0x4e, 0x04, 0x6a, 0x14, 0x8f, 0x00, 0x4f, 0x6e,
	0xef, 0xb2, 0xa4, 0x76, 0x68, 0x4e, 0x8c, 0x6f, 0x17, 0x8c, 0x28, 0xaa, 0x6a, 0x21, 0xdb, 0x66,
	0x7c, 0x6b, 0x57, 0xed, 0x6c, 0xda, 0xb5, 0x91, 0x55, 0xf6, 0xec, 0x1f, 0xde, 0xe4, 0x67, 0x58,
	0x43, 0x76, 0xa8, 0xec, 0xc0, 0xb1, 0x74, 0x53, 0xa3, 0x21, 0xfc, 0xab, 0xe2, 0x0b, 0x0e, 0x88,
	0xd1, 0x41, 0xba, 0x49, 0xab, 0x48, 0xd7, 0xaa, 0x4e, 0xa8, 0x16, 0xd4, 0x08, 0xef, 0x81, 0xc9,
	0x70, 0xe5, 0x49, 0x49, 0xc6, 0x0a, 0x8b, 0x52, 0xf7, 0xd0, 0x78, 0xa5, 0x97, 0x42, 0x91, 0x8a,
	0xbf, 0x9d, 0xb5, 0xb3, 0x89, 0xab, 0x76, 0x36, 0x65, 0x21, 0xdb, 0x35, 0x9c, 0xd2, 0x84, 0xda,
	0x2b, 0x10, 0x73, 0x40, 0x18, 0x84, 0x58, 0xc2, 0x98, 0x61, 0x8a, 0xcf, 0x39, 0x90, 0x8b, 0x92,
	0xc4, 0xcd, 0xe1, 0x2e, 0x98, 0x62, 0xe8, 0x65, 0x0b, 0x63, 0x87, 0x76, 0x9e, 0x26, 0x21, 0xf4,
	0x27, 0xb1, 0xc7, 0x0c, 0xde, 0x28, 0x14, 0x27, 0x02, 0x7a, 0xea, 0x73, 0x42, 0x09, 0xe2, 0x7b,
	0x0a, 0xf1, 0x14, 0x2c, 0x10, 0xbe, 0x5b, 0xc8, 0xd2, 0x8f, 0x5b, 0x7e, 0x8d, 0x2d, 0x8c, 0x8f,
	0x59, 0x37, 0xd7, 0xc3, 0xdd, 0x84, 0x3d, 0xdd, 0xec, 0xed, 0x1a, 0x5c, 0x07, 0xc9, 0xba, 0x77,
	0x99, 0xf0, 0xa5, 0x8b, 0xbf, 0x5f, 0xb5, 0xb3, 0xe3, 0x3e, 0x3c, 0x39, 0xa0, 0x7a, 0x2a, 0x12,
	0xcb, 0x20, 0x1b, 0x11, 0x3c, 0x6e, 0x6d, 0x16, 0x00, 0x4b, 0x8f, 0x04, 0x0c, 0x06, 0x95, 0x1a,
	0xc5, 0x1b, 0x2c, 0x40, 0x78, 0x86, 0x7e, 0x36, 0x3f, 0xf1, 0x31, 0x07, 0x16, 0x23, 0x3d, 0xc6,
	0x85, 0xfe, 0xaf, 0x07, 0x7a, 0xac, 0xb0, 0x24, 0x85, 0xf7, 0x97, 0x34, 0xc8, 0x7d, 0x38, 0xb9,
	0xfb, 0x60, 0x66, 0x90, 0x0c, 0xce, 0x81, 0x61, 0x0f, 0xbf, 0x37, 0x36, 0x31, 0xc1, 0x35, 0xd0,
	0xdb, 0x0d, 0xd6, 0x26, 0xa6, 0xf9, 0x55, 0xe9, 0x76, 0x93, 0x01, 0x49, 0xba, 0x42, 0x7e, 0xe9,
	0x5e, 0x21, 0xd4, 0x56, 0xf8, 0x96, 0x02, 0x49, 0x52, 0x07, 0xf8, 0x84, 0x03, 0xe3, 0x87, 0x1e,
	0xf3, 0x61, 0xf3, 0x80, 0x6c, 0x07, 0xf8, 0x47, 0x7f, 0x3a, 0x03, 0x76, 0x0d, 0x9f, 0x8f, 0x25,
	0xf3, 0x6b, 0x2a, 0x2e, 0x3d, 0xf2, 0xe2, 0x3f, 0xfc, 0xf8, 0xe5, 0xd9, 0x50, 0x06, 0xce, 0xc9,
	0x7d, 0xdf, 0x03, 0xdd, 0xc6, 0x86, 0xea, 0x34, 0xe1, 0x7b, 0x0e, 0xcc, 0x86, 0x5f, 0xe4, 0xd6,
	0x8e, 0x3f, 0x9e, 0x11, 0x31, 0x07, 0xee, 0x18, 0x7e, 0xfb, 0x3a, 0xea, 0x0e, 0xe8, 0xdf, 0x01,
	0xa8, 0x04, 0xd7, 0xfb, 0x41, 0xfd, 0x25, 0x92, 0x67, 0xd5, 0x96, 0x4f, 0xd9, 0x70, 0x3d, 0x80,
	0xaf, 0x39, 0x30, 0x3d, 0x60, 0x51, 0xc0, 0x8d, 0x78, 0x20, 0xc1, 0xde, 0xe1, 0x0b, 0xf1, 0x6f,
	0x74, 0xc0, 0xb7, 0x03, 0xf0, 0x55, 0xb8, 0xfc, 0x63, 0xf0, 0xbc, 0xb7, 0x8d, 0xe0, 0x3b, 0x0e,
	0xc0, 0xfe, 0xf7, 0x17, 0xca, 0x11, 0x00, 0x51, 0x7b, 0x86, 0xdf, 0x8c, 0x7d, 0xa1, 0x03, 0xfc,
	0x6f, 0x00, 0x5c, 0x80, 0x1b, 0xfd, 0xc0, 0x3e, 0x27, 0x19, 0xf5, 0xa0, 0xcc, 0x72, 0x83, 0xb8,
	0x84, 0x6f, 0xb9, 0x88, 0x17, 0x68, 0x33, 0x66, 0xdf, 0xbb, 0xe8, 0xb7, 0xae, 0x71, 0xa5, 0xc3,
	0xff, 0x57, 0xc0, 0xff, 0x27, 0x5c, 0x8d, 0xcd, 0x5f, 0xdc, 0x3b, 0xbb, 0x10, 0xb8, 0xf3, 0x0b,
	0x81, 0xfb, 0x7c, 0x21, 0x70, 0x4f, 0x2f, 0x85, 0xc4, 0xf9, 0xa5, 0x90, 0xf8, 0x74, 0x29, 0x24,
	0xee, 0x48, 0x9a, 0xee, 0x54, 0xdd, 0x23, 0xa9, 0x82, 0x6b, 0xf2, 0x46, 0x73, 0x1f, 0x1b, 0x2d,
	0x0d, 0x9b, 0x1d, 0xc7, 0xf9, 0x46, 0x41, 0x6e, 0x32, 0xdf, 0xe4, 0x63, 0x71, 0x94, 0x22, 0x3f,
	0x34, 0xb6, 0xbe, 0x07, 0x00, 0x00, 0xff, 0xff, 0x65, 0x7a, 0xbc, 0x40, 0x5f, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// TopupTxStatus queries for a specific topup tx to check its status (old
	// means already submitted)
	TopupTxStatus(ctx context.Context, in *QuerySequenceParams, opts ...grpc.CallOption) (*QuerySequenceParamsResponse, error)
	// DividendAccountByAddress queries for a specific DividendAccount by its
	// address
	DividendAccountByAddress(ctx context.Context, in *QueryDividendAccountParams, opts ...grpc.CallOption) (*QueryDividendAccountParamsResponse, error)
	// DividendAccountRoot queries for the dividend account of the genesis root
	// hash
	DividendAccountRoot(ctx context.Context, in *QueryDividendAccountRootParams, opts ...grpc.CallOption) (*QueryDividendAccountRootResponse, error)
	// VerifyAccountProof queries for the dividend account of the genesis root
	// hash
	VerifyAccountProof(ctx context.Context, in *QueryVerifyAccountProofParams, opts ...grpc.CallOption) (*QueryVerifyAccountProofResponse, error)
	// DividendAccountProof queries for the dividend account proof of a given
	// address
	DividendAccountProof(ctx context.Context, in *QueryDividendAccountProofParams, opts ...grpc.CallOption) (*QueryDividendAccountProofResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) TopupTxStatus(ctx context.Context, in *QuerySequenceParams, opts ...grpc.CallOption) (*QuerySequenceParamsResponse, error) {
	out := new(QuerySequenceParamsResponse)
	err := c.cc.Invoke(ctx, "/heimdallv2.topup.Query/TopupTxStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DividendAccountByAddress(ctx context.Context, in *QueryDividendAccountParams, opts ...grpc.CallOption) (*QueryDividendAccountParamsResponse, error) {
	out := new(QueryDividendAccountParamsResponse)
	err := c.cc.Invoke(ctx, "/heimdallv2.topup.Query/DividendAccountByAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DividendAccountRoot(ctx context.Context, in *QueryDividendAccountRootParams, opts ...grpc.CallOption) (*QueryDividendAccountRootResponse, error) {
	out := new(QueryDividendAccountRootResponse)
	err := c.cc.Invoke(ctx, "/heimdallv2.topup.Query/DividendAccountRoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VerifyAccountProof(ctx context.Context, in *QueryVerifyAccountProofParams, opts ...grpc.CallOption) (*QueryVerifyAccountProofResponse, error) {
	out := new(QueryVerifyAccountProofResponse)
	err := c.cc.Invoke(ctx, "/heimdallv2.topup.Query/VerifyAccountProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DividendAccountProof(ctx context.Context, in *QueryDividendAccountProofParams, opts ...grpc.CallOption) (*QueryDividendAccountProofResponse, error) {
	out := new(QueryDividendAccountProofResponse)
	err := c.cc.Invoke(ctx, "/heimdallv2.topup.Query/DividendAccountProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// TopupTxStatus queries for a specific topup tx to check its status (old
	// means already submitted)
	TopupTxStatus(context.Context, *QuerySequenceParams) (*QuerySequenceParamsResponse, error)
	// DividendAccountByAddress queries for a specific DividendAccount by its
	// address
	DividendAccountByAddress(context.Context, *QueryDividendAccountParams) (*QueryDividendAccountParamsResponse, error)
	// DividendAccountRoot queries for the dividend account of the genesis root
	// hash
	DividendAccountRoot(context.Context, *QueryDividendAccountRootParams) (*QueryDividendAccountRootResponse, error)
	// VerifyAccountProof queries for the dividend account of the genesis root
	// hash
	VerifyAccountProof(context.Context, *QueryVerifyAccountProofParams) (*QueryVerifyAccountProofResponse, error)
	// DividendAccountProof queries for the dividend account proof of a given
	// address
	DividendAccountProof(context.Context, *QueryDividendAccountProofParams) (*QueryDividendAccountProofResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) TopupTxStatus(ctx context.Context, req *QuerySequenceParams) (*QuerySequenceParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TopupTxStatus not implemented")
}
func (*UnimplementedQueryServer) DividendAccountByAddress(ctx context.Context, req *QueryDividendAccountParams) (*QueryDividendAccountParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DividendAccountByAddress not implemented")
}
func (*UnimplementedQueryServer) DividendAccountRoot(ctx context.Context, req *QueryDividendAccountRootParams) (*QueryDividendAccountRootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DividendAccountRoot not implemented")
}
func (*UnimplementedQueryServer) VerifyAccountProof(ctx context.Context, req *QueryVerifyAccountProofParams) (*QueryVerifyAccountProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyAccountProof not implemented")
}
func (*UnimplementedQueryServer) DividendAccountProof(ctx context.Context, req *QueryDividendAccountProofParams) (*QueryDividendAccountProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DividendAccountProof not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_TopupTxStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySequenceParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TopupTxStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/heimdallv2.topup.Query/TopupTxStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TopupTxStatus(ctx, req.(*QuerySequenceParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DividendAccountByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDividendAccountParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DividendAccountByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/heimdallv2.topup.Query/DividendAccountByAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DividendAccountByAddress(ctx, req.(*QueryDividendAccountParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DividendAccountRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDividendAccountRootParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DividendAccountRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/heimdallv2.topup.Query/DividendAccountRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DividendAccountRoot(ctx, req.(*QueryDividendAccountRootParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VerifyAccountProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVerifyAccountProofParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VerifyAccountProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/heimdallv2.topup.Query/VerifyAccountProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VerifyAccountProof(ctx, req.(*QueryVerifyAccountProofParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DividendAccountProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDividendAccountProofParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DividendAccountProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/heimdallv2.topup.Query/DividendAccountProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DividendAccountProof(ctx, req.(*QueryDividendAccountProofParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "heimdallv2.topup.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TopupTxStatus",
			Handler:    _Query_TopupTxStatus_Handler,
		},
		{
			MethodName: "DividendAccountByAddress",
			Handler:    _Query_DividendAccountByAddress_Handler,
		},
		{
			MethodName: "DividendAccountRoot",
			Handler:    _Query_DividendAccountRoot_Handler,
		},
		{
			MethodName: "VerifyAccountProof",
			Handler:    _Query_VerifyAccountProof_Handler,
		},
		{
			MethodName: "DividendAccountProof",
			Handler:    _Query_DividendAccountProof_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "heimdallv2/topup/query.proto",
}

func (m *QuerySequenceParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySequenceParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySequenceParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LogIndex != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LogIndex))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QuerySequenceParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySequenceParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySequenceParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status {
		i--
		if m.Status {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryDividendAccountParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDividendAccountParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDividendAccountParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDividendAccountParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDividendAccountParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDividendAccountParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.DividendAccount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Height) > 0 {
		i -= len(m.Height)
		copy(dAtA[i:], m.Height)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Height)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDividendAccountRootParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDividendAccountRootParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDividendAccountRootParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryDividendAccountRootResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDividendAccountRootResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDividendAccountRootResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AccountRootHash != nil {
		{
			size, err := m.AccountRootHash.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Height) > 0 {
		i -= len(m.Height)
		copy(dAtA[i:], m.Height)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Height)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVerifyAccountProofParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVerifyAccountProofParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVerifyAccountProofParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVerifyAccountProofResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVerifyAccountProofResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVerifyAccountProofResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Result {
		i--
		if m.Result {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Height) > 0 {
		i -= len(m.Height)
		copy(dAtA[i:], m.Height)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Height)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDividendAccountProofParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDividendAccountProofParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDividendAccountProofParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDividendAccountProofResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDividendAccountProofResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDividendAccountProofResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Result != nil {
		{
			size, err := m.Result.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Height) > 0 {
		i -= len(m.Height)
		copy(dAtA[i:], m.Height)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Height)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DividendAccountProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DividendAccountProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DividendAccountProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Index != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x18
	}
	if len(m.AccountProof) > 0 {
		i -= len(m.AccountProof)
		copy(dAtA[i:], m.AccountProof)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AccountProof)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.User) > 0 {
		i -= len(m.User)
		copy(dAtA[i:], m.User)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.User)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QuerySequenceParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.LogIndex != 0 {
		n += 1 + sovQuery(uint64(m.LogIndex))
	}
	return n
}

func (m *QuerySequenceParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status {
		n += 2
	}
	return n
}

func (m *QueryDividendAccountParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDividendAccountParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Height)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = m.DividendAccount.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryDividendAccountRootParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryDividendAccountRootResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Height)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.AccountRootHash != nil {
		l = m.AccountRootHash.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVerifyAccountProofParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVerifyAccountProofResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Height)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Result {
		n += 2
	}
	return n
}

func (m *QueryDividendAccountProofParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDividendAccountProofResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Height)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Result != nil {
		l = m.Result.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *DividendAccountProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.AccountProof)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovQuery(uint64(m.Index))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QuerySequenceParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySequenceParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySequenceParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogIndex", wireType)
			}
			m.LogIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LogIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySequenceParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySequenceParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySequenceParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Status = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDividendAccountParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDividendAccountParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDividendAccountParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDividendAccountParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDividendAccountParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDividendAccountParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Height = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DividendAccount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DividendAccount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDividendAccountRootParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDividendAccountRootParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDividendAccountRootParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDividendAccountRootResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDividendAccountRootResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDividendAccountRootResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Height = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountRootHash", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AccountRootHash == nil {
				m.AccountRootHash = &types.HeimdallHash{}
			}
			if err := m.AccountRootHash.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVerifyAccountProofParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVerifyAccountProofParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVerifyAccountProofParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVerifyAccountProofResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVerifyAccountProofResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVerifyAccountProofResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Height = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Result = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDividendAccountProofParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDividendAccountProofParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDividendAccountProofParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDividendAccountProofResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDividendAccountProofResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDividendAccountProofResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Height = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Result == nil {
				m.Result = &DividendAccountProof{}
			}
			if err := m.Result.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DividendAccountProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DividendAccountProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DividendAccountProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountProof", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountProof = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
