version: "2"
run:
  go: 1.24.2
  tests: true
linters:
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - goconst
    - gosec
    - makezero
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - thelper
    - tparallel
    - unconvert
    - unparam
  settings:
    goconst:
      min-len: 3
      min-occurrences: 2
      numbers: true
    gocritic:
      enabled-checks:
        - badLock
        - filepathJoin
        - sortSlice
        - sprintfQuotedString
        - syncMapLoadAndDelete
        - weakCond
        - boolExprSimplify
        - httpNoBody
        - ioutilDeprecated
        - nestingReduce
        - preferFilepathJoin
        - redundantSprint
        - stringConcatSimplify
        - timeExprSimplify
        - typeAssertChain
        - yodaStyleExpr
        - truncateCmp
        - equalFold
        - preferDecodeRune
        - preferFprint
        - preferStringWriter
        - preferWriteByte
        - sliceClear
      disabled-checks:
        - regexpMust
        - exitAfterDefer
        - dupBranchBody
        - singleCaseSwitch
        - unlambda
        - captLocal
        - commentFormatting
        - ifElseChain
        - importShadow
        - builtinShadow
      enabled-tags:
        - performance
        - diagnostic
        - opinionated
        - style
      disabled-tags:
        - experimental
    gosec:
      excludes:
        - G115
    govet:
      disable:
        - deepequalerrors
        - fieldalignment
        - shadow
        - unsafeptr
      enable-all: true
      settings:
        printf:
          funcs:
            - (github.com/ethereum/go-ethereum/log.Logger).Trace
            - (github.com/ethereum/go-ethereum/log.Logger).Debug
            - (github.com/ethereum/go-ethereum/log.Logger).Info
            - (github.com/ethereum/go-ethereum/log.Logger).Warn
            - (github.com/ethereum/go-ethereum/log.Logger).Error
            - (github.com/ethereum/go-ethereum/log.Logger).Crit
    nestif:
      min-complexity: 5
    prealloc:
      for-loops: true
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*_test\.go
      - .*\.pb\.go
      - .*\.pulsar\.go
      - api/
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: origin/develop
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/0xPolygon/heimdall-v2)
    gofmt:
      simplify: true
  exclusions:
    paths:
      - .*_test\.go
      - .*\.pb\.go
      - .*\.pulsar\.go
      - api/
      - third_party$
      - builtin$
      - examples$
