coverage:
  precision: 1
  round: down
  range: "40...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: 90%
        threshold: 1%
        informational: false

ignore:
  - "**/*_mocks.go"           # Generated mock files
  - "**/*.pb.go"              # Generated protobuf files
  - "**/*.pb.gw.go"           # Generated protobuf gateway files
  - "**/testutil/**"          # Test utilities
  - "**/simulation/**"        # Simulation code
  - "cmd/heimdalld/cmd/migration/**"  # Migration scripts
  - "**/*_test.go"            # Test files themselves

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# Only calculate coverage for specified packages
flags:
  core:
    paths:
      - app/
      - bridge/
      - client/
      - cmd/
      - common/
      - file/
      - helper/
      - sidetxs/
      - types/
      - version/
      - x/
