// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: heimdallv2/milestone/v1/tx.proto

package milestonev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_Milestone_FullMethodName        = "/heimdallv2.milestone.v1.Msg/Milestone"
	Msg_MilestoneTimeout_FullMethodName = "/heimdallv2.milestone.v1.Msg/MilestoneTimeout"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// Milestone defines a method for milestone
	Milestone(ctx context.Context, in *MsgMilestone, opts ...grpc.CallOption) (*MsgMilestoneResponse, error)
	// MilestoneTimeout defines a method for MilestoneTimeout
	MilestoneTimeout(ctx context.Context, in *MsgMilestoneTimeout, opts ...grpc.CallOption) (*MsgMilestoneTimeoutResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Milestone(ctx context.Context, in *MsgMilestone, opts ...grpc.CallOption) (*MsgMilestoneResponse, error) {
	out := new(MsgMilestoneResponse)
	err := c.cc.Invoke(ctx, Msg_Milestone_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MilestoneTimeout(ctx context.Context, in *MsgMilestoneTimeout, opts ...grpc.CallOption) (*MsgMilestoneTimeoutResponse, error) {
	out := new(MsgMilestoneTimeoutResponse)
	err := c.cc.Invoke(ctx, Msg_MilestoneTimeout_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// Milestone defines a method for milestone
	Milestone(context.Context, *MsgMilestone) (*MsgMilestoneResponse, error)
	// MilestoneTimeout defines a method for MilestoneTimeout
	MilestoneTimeout(context.Context, *MsgMilestoneTimeout) (*MsgMilestoneTimeoutResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) Milestone(context.Context, *MsgMilestone) (*MsgMilestoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Milestone not implemented")
}
func (UnimplementedMsgServer) MilestoneTimeout(context.Context, *MsgMilestoneTimeout) (*MsgMilestoneTimeoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MilestoneTimeout not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_Milestone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMilestone)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Milestone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_Milestone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Milestone(ctx, req.(*MsgMilestone))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MilestoneTimeout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMilestoneTimeout)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MilestoneTimeout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_MilestoneTimeout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MilestoneTimeout(ctx, req.(*MsgMilestoneTimeout))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "heimdallv2.milestone.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Milestone",
			Handler:    _Msg_Milestone_Handler,
		},
		{
			MethodName: "MilestoneTimeout",
			Handler:    _Msg_MilestoneTimeout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "heimdallv2/milestone/v1/tx.proto",
}
