// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/types/stake.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/cometbft/cometbft/abci/types"
	_ "github.com/cometbft/cometbft/proto/tendermint/types"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HeimdallValidator struct {
	ValId            uint64     `protobuf:"varint,1,opt,name=val_id,json=valId,proto3" json:"val_id,omitempty"`
	StartEpoch       uint64     `protobuf:"varint,2,opt,name=start_epoch,json=startEpoch,proto3" json:"start_epoch,omitempty"`
	EndEpoch         uint64     `protobuf:"varint,3,opt,name=end_epoch,json=endEpoch,proto3" json:"end_epoch,omitempty"`
	Nonce            uint64     `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	VotingPower      int64      `protobuf:"varint,5,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"`
	PubKey           *types.Any `protobuf:"bytes,6,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Signer           string     `protobuf:"bytes,7,opt,name=signer,proto3" json:"signer,omitempty"`
	LastUpdated      string     `protobuf:"bytes,8,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Jailed           bool       `protobuf:"varint,9,opt,name=jailed,proto3" json:"jailed,omitempty"`
	ProposerPriority int64      `protobuf:"varint,10,opt,name=proposer_priority,json=proposerPriority,proto3" json:"proposer_priority,omitempty"`
}

func (m *HeimdallValidator) Reset()         { *m = HeimdallValidator{} }
func (m *HeimdallValidator) String() string { return proto.CompactTextString(m) }
func (*HeimdallValidator) ProtoMessage()    {}
func (*HeimdallValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_b49257be9c93d4e3, []int{0}
}
func (m *HeimdallValidator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HeimdallValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HeimdallValidator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HeimdallValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeimdallValidator.Merge(m, src)
}
func (m *HeimdallValidator) XXX_Size() int {
	return m.Size()
}
func (m *HeimdallValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_HeimdallValidator.DiscardUnknown(m)
}

var xxx_messageInfo_HeimdallValidator proto.InternalMessageInfo

func (m *HeimdallValidator) GetValId() uint64 {
	if m != nil {
		return m.ValId
	}
	return 0
}

func (m *HeimdallValidator) GetStartEpoch() uint64 {
	if m != nil {
		return m.StartEpoch
	}
	return 0
}

func (m *HeimdallValidator) GetEndEpoch() uint64 {
	if m != nil {
		return m.EndEpoch
	}
	return 0
}

func (m *HeimdallValidator) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *HeimdallValidator) GetVotingPower() int64 {
	if m != nil {
		return m.VotingPower
	}
	return 0
}

func (m *HeimdallValidator) GetPubKey() *types.Any {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *HeimdallValidator) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *HeimdallValidator) GetLastUpdated() string {
	if m != nil {
		return m.LastUpdated
	}
	return ""
}

func (m *HeimdallValidator) GetJailed() bool {
	if m != nil {
		return m.Jailed
	}
	return false
}

func (m *HeimdallValidator) GetProposerPriority() int64 {
	if m != nil {
		return m.ProposerPriority
	}
	return 0
}

// HeimdallHash this following defines the
// hash
type HeimdallHash struct {
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *HeimdallHash) Reset()         { *m = HeimdallHash{} }
func (m *HeimdallHash) String() string { return proto.CompactTextString(m) }
func (*HeimdallHash) ProtoMessage()    {}
func (*HeimdallHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_b49257be9c93d4e3, []int{1}
}
func (m *HeimdallHash) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HeimdallHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HeimdallHash.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HeimdallHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeimdallHash.Merge(m, src)
}
func (m *HeimdallHash) XXX_Size() int {
	return m.Size()
}
func (m *HeimdallHash) XXX_DiscardUnknown() {
	xxx_messageInfo_HeimdallHash.DiscardUnknown(m)
}

var xxx_messageInfo_HeimdallHash proto.InternalMessageInfo

func (m *HeimdallHash) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

// TxHash this following defines the
// hash of the transaction
type TxHash struct {
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *TxHash) Reset()         { *m = TxHash{} }
func (m *TxHash) String() string { return proto.CompactTextString(m) }
func (*TxHash) ProtoMessage()    {}
func (*TxHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_b49257be9c93d4e3, []int{2}
}
func (m *TxHash) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TxHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TxHash.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TxHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxHash.Merge(m, src)
}
func (m *TxHash) XXX_Size() int {
	return m.Size()
}
func (m *TxHash) XXX_DiscardUnknown() {
	xxx_messageInfo_TxHash.DiscardUnknown(m)
}

var xxx_messageInfo_TxHash proto.InternalMessageInfo

func (m *TxHash) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

// ValidatorSet this following defines the
// set of validator
type ValidatorSet struct {
	Validators []*HeimdallValidator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	Proposer   *HeimdallValidator   `protobuf:"bytes,2,opt,name=proposer,proto3" json:"proposer,omitempty"`
	// total voting power
	TotalVotingPower int64 `protobuf:"varint,3,opt,name=total_voting_power,json=totalVotingPower,proto3" json:"total_voting_power,omitempty"`
}

func (m *ValidatorSet) Reset()         { *m = ValidatorSet{} }
func (m *ValidatorSet) String() string { return proto.CompactTextString(m) }
func (*ValidatorSet) ProtoMessage()    {}
func (*ValidatorSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_b49257be9c93d4e3, []int{3}
}
func (m *ValidatorSet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorSet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorSet.Merge(m, src)
}
func (m *ValidatorSet) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorSet.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorSet proto.InternalMessageInfo

func init() {
	proto.RegisterType((*HeimdallValidator)(nil), "cosmos.types.HeimdallValidator")
	proto.RegisterType((*HeimdallHash)(nil), "cosmos.types.HeimdallHash")
	proto.RegisterType((*TxHash)(nil), "cosmos.types.TxHash")
	proto.RegisterType((*ValidatorSet)(nil), "cosmos.types.ValidatorSet")
}

func init() { proto.RegisterFile("cosmos/types/stake.proto", fileDescriptor_b49257be9c93d4e3) }

var fileDescriptor_b49257be9c93d4e3 = []byte{
	// 595 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x3f, 0x6f, 0x13, 0x31,
	0x18, 0xc6, 0x63, 0x92, 0x5c, 0x13, 0x27, 0x03, 0xb5, 0x3a, 0x5c, 0xff, 0x5d, 0x42, 0x07, 0x74,
	0x20, 0x71, 0x27, 0xb5, 0x62, 0xe9, 0xd6, 0x48, 0x40, 0x81, 0xa5, 0x6a, 0xa1, 0x03, 0xcb, 0xc9,
	0x89, 0xcd, 0xc5, 0xf4, 0x62, 0x5b, 0xb6, 0x13, 0x7a, 0xdf, 0x80, 0x91, 0x8f, 0xd0, 0x91, 0x91,
	0x81, 0x0f, 0x51, 0xc1, 0x52, 0x31, 0x31, 0x21, 0x68, 0x07, 0xf8, 0x18, 0x28, 0x3e, 0x5f, 0x7b,
	0x2d, 0x0b, 0x2c, 0x97, 0xf8, 0xfd, 0x3d, 0xaf, 0xfd, 0xbe, 0xaf, 0x1f, 0x43, 0x7f, 0x24, 0xf4,
	0x44, 0xe8, 0xd8, 0xe4, 0x92, 0xea, 0x58, 0x1b, 0x7c, 0x44, 0x23, 0xa9, 0x84, 0x11, 0xa8, 0x5b,
	0x90, 0xc8, 0x92, 0x95, 0xa5, 0x54, 0xa4, 0xc2, 0x82, 0x78, 0xfe, 0xaf, 0xd0, 0xac, 0x2c, 0xa7,
	0x42, 0xa4, 0x19, 0x8d, 0xed, 0x6a, 0x38, 0x7d, 0x1d, 0x63, 0x9e, 0x3b, 0x14, 0xdc, 0x44, 0x64,
	0xaa, 0xb0, 0x61, 0x82, 0x3b, 0xde, 0xbb, 0xc9, 0x0d, 0x9b, 0x50, 0x6d, 0xf0, 0x44, 0x96, 0x7b,
	0x17, 0xe7, 0x27, 0xc5, 0xa1, 0xae, 0x98, 0x02, 0x2d, 0xe2, 0x09, 0xe3, 0x22, 0xb6, 0x5f, 0x17,
	0x5a, 0x33, 0x94, 0x13, 0xaa, 0x26, 0x8c, 0x1b, 0xd7, 0x8b, 0xfd, 0x3a, 0xba, 0x5a, 0xa1, 0x78,
	0x38, 0x62, 0x55, 0xb8, 0xf1, 0xa5, 0x0e, 0x17, 0x77, 0x29, 0x9b, 0x10, 0x9c, 0x65, 0x87, 0x38,
	0x63, 0x04, 0x1b, 0xa1, 0xd0, 0x1a, 0xf4, 0x66, 0x38, 0x4b, 0x18, 0xf1, 0x41, 0x1f, 0x84, 0x8d,
	0x41, 0xf3, 0xc3, 0xaf, 0x8f, 0xf7, 0xc1, 0x7e, 0x73, 0x86, 0xb3, 0xa7, 0x04, 0xdd, 0x85, 0x1d,
	0x6d, 0xb0, 0x32, 0x09, 0x95, 0x62, 0x34, 0xf6, 0x6f, 0x55, 0x25, 0xd0, 0x92, 0x47, 0x73, 0x80,
	0x36, 0x60, 0x9b, 0x72, 0xe2, 0x54, 0xf5, 0xaa, 0xaa, 0x45, 0x39, 0x29, 0x34, 0xab, 0xb0, 0xc9,
	0x05, 0x1f, 0x51, 0xbf, 0x71, 0xed, 0x20, 0x1b, 0x43, 0x21, 0xec, 0xce, 0x84, 0x61, 0x3c, 0x4d,
	0xa4, 0x78, 0x4b, 0x95, 0xdf, 0xec, 0x83, 0xb0, 0x5e, 0x6a, 0x3a, 0x05, 0xda, 0x9b, 0x13, 0xf4,
	0x04, 0x2e, 0xc8, 0xe9, 0x30, 0x39, 0xa2, 0xb9, 0xef, 0xf5, 0x41, 0xd8, 0xd9, 0x5c, 0x8a, 0x8a,
	0x11, 0x47, 0xe5, 0x88, 0xa3, 0x1d, 0x9e, 0x0f, 0xfc, 0xcf, 0x9f, 0x1e, 0x2c, 0xb9, 0x69, 0x8e,
	0x54, 0x2e, 0x8d, 0x88, 0xf6, 0xa6, 0xc3, 0xe7, 0x34, 0xdf, 0xf7, 0xa4, 0xfd, 0x45, 0x0f, 0xa1,
	0xa7, 0x59, 0xca, 0xa9, 0xf2, 0x17, 0xfa, 0x20, 0x6c, 0x0f, 0xd6, 0xbf, 0x5e, 0x65, 0xec, 0x10,
	0xa2, 0xa8, 0xd6, 0x07, 0x46, 0x31, 0x9e, 0x16, 0x45, 0x38, 0xf1, 0xbc, 0xd2, 0x0c, 0x6b, 0x93,
	0x4c, 0x25, 0xc1, 0x86, 0x12, 0xbf, 0x65, 0x93, 0xcb, 0x4a, 0xe7, 0xe8, 0x65, 0x41, 0xd0, 0x3a,
	0xf4, 0xde, 0x60, 0x96, 0x51, 0xe2, 0xb7, 0xfb, 0x20, 0x6c, 0x95, 0x1a, 0x17, 0x44, 0x9b, 0x70,
	0x51, 0x2a, 0x21, 0x85, 0xa6, 0x2a, 0x91, 0x8a, 0x09, 0xc5, 0x4c, 0xee, 0xc3, 0x6a, 0xdf, 0xb7,
	0x4b, 0xbe, 0xe7, 0xf0, 0x76, 0xeb, 0xdd, 0x49, 0x0f, 0xfc, 0x3e, 0xe9, 0x81, 0x8d, 0x18, 0x76,
	0xcb, 0xcb, 0xdc, 0xc5, 0x7a, 0x8c, 0x96, 0x61, 0x63, 0x8c, 0xf5, 0xd8, 0xde, 0x62, 0xb7, 0xdc,
	0xc0, 0x86, 0xb6, 0x1b, 0x36, 0xe1, 0x1e, 0xf4, 0x5e, 0x1c, 0xff, 0x9b, 0xf4, 0x27, 0x80, 0xdd,
	0x4b, 0x87, 0x1c, 0x50, 0x83, 0x9e, 0x41, 0x38, 0x2b, 0xd7, 0xda, 0x07, 0xfd, 0x7a, 0xd8, 0xd9,
	0xec, 0x45, 0xd5, 0x87, 0x13, 0xfd, 0xe5, 0xac, 0x41, 0xfb, 0xf4, 0x7b, 0x0f, 0x38, 0xab, 0x5c,
	0x65, 0xa3, 0xc7, 0xb0, 0x55, 0xb6, 0x65, 0xfd, 0xf4, 0x7f, 0x3b, 0x5d, 0xe6, 0xa2, 0x2d, 0x88,
	0x8c, 0x30, 0x38, 0x4b, 0xae, 0xf9, 0xa6, 0x7e, 0x6d, 0x7e, 0x56, 0x70, 0x78, 0x65, 0x1e, 0x3b,
	0xbf, 0xda, 0xbc, 0xc7, 0xc1, 0x9d, 0xd3, 0xf3, 0x00, 0x9c, 0x9d, 0x07, 0xe0, 0xc7, 0x79, 0x00,
	0xde, 0x5f, 0x04, 0xb5, 0xb3, 0x8b, 0xa0, 0xf6, 0xed, 0x22, 0xa8, 0xbd, 0x5a, 0x38, 0x2e, 0x9e,
	0xcd, 0xd0, 0xb3, 0x86, 0xda, 0xfa, 0x13, 0x00, 0x00, 0xff, 0xff, 0xac, 0xfc, 0x4e, 0x39, 0x3c,
	0x04, 0x00, 0x00,
}

func (this *HeimdallValidator) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HeimdallValidator)
	if !ok {
		that2, ok := that.(HeimdallValidator)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ValId != that1.ValId {
		return false
	}
	if this.StartEpoch != that1.StartEpoch {
		return false
	}
	if this.EndEpoch != that1.EndEpoch {
		return false
	}
	if this.Nonce != that1.Nonce {
		return false
	}
	if this.VotingPower != that1.VotingPower {
		return false
	}
	if !this.PubKey.Equal(that1.PubKey) {
		return false
	}
	if this.Signer != that1.Signer {
		return false
	}
	if this.LastUpdated != that1.LastUpdated {
		return false
	}
	if this.Jailed != that1.Jailed {
		return false
	}
	if this.ProposerPriority != that1.ProposerPriority {
		return false
	}
	return true
}
func (this *HeimdallHash) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HeimdallHash)
	if !ok {
		that2, ok := that.(HeimdallHash)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Hash, that1.Hash) {
		return false
	}
	return true
}
func (this *TxHash) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TxHash)
	if !ok {
		that2, ok := that.(TxHash)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Hash, that1.Hash) {
		return false
	}
	return true
}
func (this *ValidatorSet) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ValidatorSet)
	if !ok {
		that2, ok := that.(ValidatorSet)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Validators) != len(that1.Validators) {
		return false
	}
	for i := range this.Validators {
		if !this.Validators[i].Equal(that1.Validators[i]) {
			return false
		}
	}
	if !this.Proposer.Equal(that1.Proposer) {
		return false
	}
	if this.TotalVotingPower != that1.TotalVotingPower {
		return false
	}
	return true
}
func (m *HeimdallValidator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HeimdallValidator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HeimdallValidator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProposerPriority != 0 {
		i = encodeVarintStake(dAtA, i, uint64(m.ProposerPriority))
		i--
		dAtA[i] = 0x50
	}
	if m.Jailed {
		i--
		if m.Jailed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if len(m.LastUpdated) > 0 {
		i -= len(m.LastUpdated)
		copy(dAtA[i:], m.LastUpdated)
		i = encodeVarintStake(dAtA, i, uint64(len(m.LastUpdated)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintStake(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x3a
	}
	if m.PubKey != nil {
		{
			size, err := m.PubKey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStake(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.VotingPower != 0 {
		i = encodeVarintStake(dAtA, i, uint64(m.VotingPower))
		i--
		dAtA[i] = 0x28
	}
	if m.Nonce != 0 {
		i = encodeVarintStake(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x20
	}
	if m.EndEpoch != 0 {
		i = encodeVarintStake(dAtA, i, uint64(m.EndEpoch))
		i--
		dAtA[i] = 0x18
	}
	if m.StartEpoch != 0 {
		i = encodeVarintStake(dAtA, i, uint64(m.StartEpoch))
		i--
		dAtA[i] = 0x10
	}
	if m.ValId != 0 {
		i = encodeVarintStake(dAtA, i, uint64(m.ValId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *HeimdallHash) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HeimdallHash) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HeimdallHash) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintStake(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TxHash) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TxHash) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TxHash) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintStake(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorSet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorSet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorSet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalVotingPower != 0 {
		i = encodeVarintStake(dAtA, i, uint64(m.TotalVotingPower))
		i--
		dAtA[i] = 0x18
	}
	if m.Proposer != nil {
		{
			size, err := m.Proposer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStake(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Validators) > 0 {
		for iNdEx := len(m.Validators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Validators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintStake(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintStake(dAtA []byte, offset int, v uint64) int {
	offset -= sovStake(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HeimdallValidator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ValId != 0 {
		n += 1 + sovStake(uint64(m.ValId))
	}
	if m.StartEpoch != 0 {
		n += 1 + sovStake(uint64(m.StartEpoch))
	}
	if m.EndEpoch != 0 {
		n += 1 + sovStake(uint64(m.EndEpoch))
	}
	if m.Nonce != 0 {
		n += 1 + sovStake(uint64(m.Nonce))
	}
	if m.VotingPower != 0 {
		n += 1 + sovStake(uint64(m.VotingPower))
	}
	if m.PubKey != nil {
		l = m.PubKey.Size()
		n += 1 + l + sovStake(uint64(l))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovStake(uint64(l))
	}
	l = len(m.LastUpdated)
	if l > 0 {
		n += 1 + l + sovStake(uint64(l))
	}
	if m.Jailed {
		n += 2
	}
	if m.ProposerPriority != 0 {
		n += 1 + sovStake(uint64(m.ProposerPriority))
	}
	return n
}

func (m *HeimdallHash) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovStake(uint64(l))
	}
	return n
}

func (m *TxHash) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovStake(uint64(l))
	}
	return n
}

func (m *ValidatorSet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Validators) > 0 {
		for _, e := range m.Validators {
			l = e.Size()
			n += 1 + l + sovStake(uint64(l))
		}
	}
	if m.Proposer != nil {
		l = m.Proposer.Size()
		n += 1 + l + sovStake(uint64(l))
	}
	if m.TotalVotingPower != 0 {
		n += 1 + sovStake(uint64(m.TotalVotingPower))
	}
	return n
}

func sovStake(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStake(x uint64) (n int) {
	return sovStake(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HeimdallValidator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStake
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HeimdallValidator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HeimdallValidator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValId", wireType)
			}
			m.ValId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartEpoch", wireType)
			}
			m.StartEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndEpoch", wireType)
			}
			m.EndEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingPower", wireType)
			}
			m.VotingPower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VotingPower |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PubKey == nil {
				m.PubKey = &types.Any{}
			}
			if err := m.PubKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdated", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastUpdated = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Jailed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Jailed = bool(v != 0)
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposerPriority", wireType)
			}
			m.ProposerPriority = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposerPriority |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStake(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStake
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HeimdallHash) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStake
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HeimdallHash: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HeimdallHash: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = append(m.Hash[:0], dAtA[iNdEx:postIndex]...)
			if m.Hash == nil {
				m.Hash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStake(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStake
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TxHash) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStake
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TxHash: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TxHash: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = append(m.Hash[:0], dAtA[iNdEx:postIndex]...)
			if m.Hash == nil {
				m.Hash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStake(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStake
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorSet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStake
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorSet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorSet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validators = append(m.Validators, &HeimdallValidator{})
			if err := m.Validators[len(m.Validators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Proposer == nil {
				m.Proposer = &HeimdallValidator{}
			}
			if err := m.Proposer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalVotingPower", wireType)
			}
			m.TotalVotingPower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalVotingPower |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStake(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStake
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStake(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStake
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStake
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStake
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStake
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStake
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStake
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStake        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStake          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStake = fmt.Errorf("proto: unexpected end of group")
)
