// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: heimdallv2/clerk/v1beta1/query.proto

package clerkv1beta1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_NewQueryRecordParams_FullMethodName              = "/heimdallv2.clerk.v1beta1.Query/NewQueryRecordParams"
	Query_NewQueryRecordSequenceParams_FullMethodName      = "/heimdallv2.clerk.v1beta1.Query/NewQueryRecordSequenceParams"
	Query_NewQueryTimeRangePaginationParams_FullMethodName = "/heimdallv2.clerk.v1beta1.Query/NewQueryTimeRangePaginationParams"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// TODO HV2 - check url
	NewQueryRecordParams(ctx context.Context, in *NewQueryRecordParamsRequest, opts ...grpc.CallOption) (*QueryRecordParams, error)
	// TODO HV2 - check url
	NewQueryRecordSequenceParams(ctx context.Context, in *NewQueryRecordSequenceParamsRequest, opts ...grpc.CallOption) (*QueryRecordSequenceParams, error)
	// TODO HV2 - check url
	NewQueryTimeRangePaginationParams(ctx context.Context, in *NewQueryTimeRangePaginationParamsRequest, opts ...grpc.CallOption) (*QueryRecordTimePaginationParams, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) NewQueryRecordParams(ctx context.Context, in *NewQueryRecordParamsRequest, opts ...grpc.CallOption) (*QueryRecordParams, error) {
	out := new(QueryRecordParams)
	err := c.cc.Invoke(ctx, Query_NewQueryRecordParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NewQueryRecordSequenceParams(ctx context.Context, in *NewQueryRecordSequenceParamsRequest, opts ...grpc.CallOption) (*QueryRecordSequenceParams, error) {
	out := new(QueryRecordSequenceParams)
	err := c.cc.Invoke(ctx, Query_NewQueryRecordSequenceParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NewQueryTimeRangePaginationParams(ctx context.Context, in *NewQueryTimeRangePaginationParamsRequest, opts ...grpc.CallOption) (*QueryRecordTimePaginationParams, error) {
	out := new(QueryRecordTimePaginationParams)
	err := c.cc.Invoke(ctx, Query_NewQueryTimeRangePaginationParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// TODO HV2 - check url
	NewQueryRecordParams(context.Context, *NewQueryRecordParamsRequest) (*QueryRecordParams, error)
	// TODO HV2 - check url
	NewQueryRecordSequenceParams(context.Context, *NewQueryRecordSequenceParamsRequest) (*QueryRecordSequenceParams, error)
	// TODO HV2 - check url
	NewQueryTimeRangePaginationParams(context.Context, *NewQueryTimeRangePaginationParamsRequest) (*QueryRecordTimePaginationParams, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) NewQueryRecordParams(context.Context, *NewQueryRecordParamsRequest) (*QueryRecordParams, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewQueryRecordParams not implemented")
}
func (UnimplementedQueryServer) NewQueryRecordSequenceParams(context.Context, *NewQueryRecordSequenceParamsRequest) (*QueryRecordSequenceParams, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewQueryRecordSequenceParams not implemented")
}
func (UnimplementedQueryServer) NewQueryTimeRangePaginationParams(context.Context, *NewQueryTimeRangePaginationParamsRequest) (*QueryRecordTimePaginationParams, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewQueryTimeRangePaginationParams not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_NewQueryRecordParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewQueryRecordParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NewQueryRecordParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_NewQueryRecordParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NewQueryRecordParams(ctx, req.(*NewQueryRecordParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NewQueryRecordSequenceParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewQueryRecordSequenceParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NewQueryRecordSequenceParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_NewQueryRecordSequenceParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NewQueryRecordSequenceParams(ctx, req.(*NewQueryRecordSequenceParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NewQueryTimeRangePaginationParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewQueryTimeRangePaginationParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NewQueryTimeRangePaginationParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_NewQueryTimeRangePaginationParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NewQueryTimeRangePaginationParams(ctx, req.(*NewQueryTimeRangePaginationParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "heimdallv2.clerk.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewQueryRecordParams",
			Handler:    _Query_NewQueryRecordParams_Handler,
		},
		{
			MethodName: "NewQueryRecordSequenceParams",
			Handler:    _Query_NewQueryRecordSequenceParams_Handler,
		},
		{
			MethodName: "NewQueryTimeRangePaginationParams",
			Handler:    _Query_NewQueryTimeRangePaginationParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "heimdallv2/clerk/v1beta1/query.proto",
}
