name: Govuln

on:
  schedule:
    # Daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  govulncheck:
    name: Run govulncheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true
      - name: govulncheck
        run: make vulncheck
