name: Kurtosis E2E Tests

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'
    types: [opened, synchronize]

concurrency:
  group: kurtosis-e2e-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  ENCLAVE_NAME: kurtosis-e2e

jobs:
  build-bor:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout bor
        uses: actions/checkout@v5
        with:
          repository: 0xPolygon/bor
          ref: develop

      - name: Build docker image
        run: docker build -t bor:local --file Dockerfile .

      - name: Save image
        run: docker save bor:local | gzip > bor-image.tar.gz

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: bor-image
          path: bor-image.tar.gz
          retention-days: 1

  build-heimdall-v2:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout heimdall-v2
        uses: actions/checkout@v5

      - name: Build docker image
        run: docker build -t heimdall-v2:local --file Dockerfile .

      - name: Save image
        run: docker save heimdall-v2:local | gzip > heimdall-v2-image.tar.gz

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: heimdall-v2-image
          path: heimdall-v2-image.tar.gz
          retention-days: 1

  e2e-tests:
    needs:
      - build-bor
      - build-heimdall-v2
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # These permissions are required to log in to GCR
    permissions:
      contents: read
      actions: write
      id-token: write
    steps:
      # Set up kurtosis
      - name: Checkout kurtosis-pos
        uses: actions/checkout@v5
        with:
          repository: 0xPolygon/kurtosis-pos
          ref: hv2/tx-eip1559-gas-price-configs

      # This step will free disk space and thus remove any docker images previously built
      - name: Pre kurtosis run
        uses: ./.github/actions/setup
        with:
          main_branch: develop
          docker_username: ${{ secrets.DOCKERHUB }}
          docker_token: ${{ secrets.DOCKERHUB_KEY }}

      - name: Checkout pos-workflows
        uses: actions/checkout@v5
        with:
          repository: 0xPolygon/pos-workflows
          ref: main
          path: pos-workflows

      - name: Copy kurtosis config
        run: cp ./pos-workflows/.github/configs/kurtosis-e2e.yml ./kurtosis-e2e.yml

      # Load images
      - name: Download bor image
        uses: actions/download-artifact@v4
        with:
          name: bor-image

      - name: Download heimdall-v2 image
        uses: actions/download-artifact@v4
        with:
          name: heimdall-v2-image

      - name: Load bor image
        run: |
          gunzip -c bor-image.tar.gz | docker load
          echo "Loaded bor image:"
          docker images bor:local --format "{{.ID}} {{.CreatedAt}}"

      - name: Load heimdall-v2 image
        run: |
          gunzip -c heimdall-v2-image.tar.gz | docker load
          echo "Loaded heimdall-v2 image:"
          docker images heimdall-v2:local --format "{{.ID}} {{.CreatedAt}}"

      # Deploy kurtosis enclave
      - name: Kurtosis run
        run: kurtosis run --args-file=kurtosis-e2e.yml --enclave=${{ env.ENCLAVE_NAME }} .

      - name: Inspect enclave
        run: kurtosis enclave inspect ${{ env.ENCLAVE_NAME }}

      - name: Sleep for 1 minute
        run: sleep 60

      - name: Test state syncs
        uses: ./.github/actions/test-state-sync
        with:
          enclave_name: ${{ env.ENCLAVE_NAME }}
          agglayer_e2e_tag: 2687c0c751e7cae2deaf4e99b13ae0d0ef97b2d7

      - name: Add new validator
        shell: bash
        working-directory: agglayer-e2e
        run: bats --show-output-of-passing-tests --filter 'add new validator' tests/pos/validator.bats

      - name: Update validator stake
        shell: bash
        working-directory: agglayer-e2e
        run: bats --show-output-of-passing-tests --filter 'update validator stake' tests/pos/validator.bats

      - name: Delegate MATIC/POL to a validator
        shell: bash
        working-directory: agglayer-e2e
        run: bats --show-output-of-passing-tests --filter 'delegate MATIC/POL to a validator' tests/pos/validator.bats

      - name: Undelegate MATIC/POL from a validator
        shell: bash
        working-directory: agglayer-e2e
        run: bats --show-output-of-passing-tests --filter 'undelegate MATIC/POL from a validator' tests/pos/validator.bats

      - name: Remove validator
        shell: bash
        working-directory: agglayer-e2e
        run: bats --show-output-of-passing-tests --filter 'remove validator' tests/pos/validator.bats

      - name: Run smoke tests
        run: bash ./pos-workflows/tests/kurtosis_smoke_test.sh

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Run set producer downtime test
        working-directory: pos-workflows/tests/producer_planned_downtime
        run: go run .

      # Clean up
      - name: Post kurtosis run
        if: always()
        uses: ./.github/actions/cleanup
        with:
          main_branch: develop
          enclave_name: ${{ env.ENCLAVE_NAME }}
