name: Stateless Sync Tests

on:
  push:
    branches:
      - 'stateless_sync'
  pull_request:
    branches:
      - 'stateless_sync'
    types: [opened, synchronize, reopened]

concurrency:
  group: stateless-sync-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  ENCLAVE_NAME: kurtosis-stateless-e2e

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      # This is needed because the job fails with "System.IO.IOException: No space left on device".
      - name: Free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # 2023/10/19
        with:
          tool-cache: true

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install build-essential

      - name: Checkout heimdall-v2
        uses: actions/checkout@v5
        with:
          path: heimdall-v2

      - name: Checkout bor
        uses: actions/checkout@v5
        with:
          repository: 0xPolygon/bor
          ref: stateless_sync
          path: bor

      - name: Checkout pos-workflows
        uses: actions/checkout@v5
        with:
          repository: 0xPolygon/pos-workflows
          ref: main
          path: pos-workflows

      - name: Checkout kurtosis-pos
        uses: actions/checkout@v5
        with:
          repository: 0xPolygon/kurtosis-pos
          ref: stateless
          path: kurtosis-pos

      - name: Pre kurtosis run
        uses: ./pos-workflows/.github/actions/kurtosis-pre-run
        with:
          docker_username: ${{ secrets.DOCKERHUB }}
          docker_token: ${{ secrets.DOCKERHUB_KEY }}

      - name: Build bor docker image
        run: |
          cd bor
          docker build -t bor:local --file Dockerfile .

      - name: Build heimdall-v2 docker image
        run: |
          cd heimdall-v2
          docker build -t heimdall-v2:local --file Dockerfile .

      - name: Copy kurtosis config
        run: cp ./pos-workflows/.github/configs/kurtosis-stateless-e2e.yml ./kurtosis-pos/kurtosis-stateless-e2e.yml

      - name: Kurtosis run
        run: |
          cd kurtosis-pos
          kurtosis run --args-file=kurtosis-stateless-e2e.yml --enclave ${{ env.ENCLAVE_NAME }} .

      - name: Inspect enclave
        run: kurtosis enclave inspect ${{ env.ENCLAVE_NAME }}

      - name: Run stateless sync tests
        run: |
          cd pos-workflows
          bash tests/stateless_tests/kurtosis_stateless_test.sh

      - name: Test state syncs (post VeBlop HF)
        run: kurtosis service exec ${{ env.ENCLAVE_NAME }} test-runner "bats --filter-tags pos,bridge,l1,l2 --recursive tests/"

      - name: Post kurtosis run
        if: always()
        uses: ./pos-workflows/.github/actions/kurtosis-post-run
        with:
          enclave_name: ${{ env.ENCLAVE_NAME }}
