FROM golang:latest

ARG HEIMDALL_DIR=/var/lib/heimdall
ENV HEIMDALL_DIR=$HEIMDALL_DIR

RUN apt-get update -y && apt-get upgrade -y \
    && apt install build-essential git -y \
    && mkdir -p $HEIMDALL_DIR

WORKDIR ${HEIMDALL_DIR}

# Copy dependency files first to leverage Docker cache
COPY go.mod go.sum ./
RUN go mod download

# Copy the remaining source code
COPY . .

# Build the application and copy the binary

RUN make heimdalld && cp build/heimdalld /usr/local/bin/

ENV SHELL /bin/bash
EXPOSE 1317 26656 26657