FROM golang:latest

ARG HEIMDALL_DIR=/var/lib/heimdall
ENV HEIMDALL_DIR=$HEIMDALL_DIR
# Add this line to fix the 0x%21polygon issue on Mac
ENV GOPRIVATE=github.com/0xPolygon/*

RUN apt-get update -y && apt-get upgrade -y \
    && apt install build-essential git -y \
    && mkdir -p $HEIMDALL_DIR

WORKDIR ${HEIMDALL_DIR}
COPY . .

RUN make heimdalld && cp build/heimdalld /usr/local/bin/
RUN chmod +x ./engine-api-poc/init-heimdalld-script.sh
RUN chmod +x ./engine-api-poc/start-heimdalld-script.sh

ENV SHELL /bin/bash
EXPOSE 1317 26656 26657